# settings_language.py

AVAILABLE_LANGUAGES = [
    ("en", "English"),
    ("it", "Italiano"),
    ("es", "Español"),
    ("fr", "Français"),
    ("de", "Deutsch"),
]

TRANSLATIONS = {
    "en": {
        "app_title": "UE Offline Agent – Chat",
        "menu_file": "File",
        "menu_save": "Save chat…",
        "menu_exit": "Exit",
        "menu_edit": "Edit",
        "menu_settings": "Settings…",
        "status_ready": "Ready",
        "status_thinking": "Thinking…",
        "status_stop_req": "Stop requested…",
        "status_no_model": "No model selected. Go to Edit → Settings…",
        "hint_ready": "Ready. Type a message and press Enter (or click Send).",
        "me_label": "You",
        "agent_label": "Agent",
        "btn_send": "Send",
        "btn_stop": "Stop",
        "dlg_save_title": "Save chat",
        "dlg_chat_empty": "The chat is empty.",
        "dlg_saved_to": "Saved to:",
        "dlg_err_saving": "Save error:",
        "settings_title": "Settings",
        "tab_models": "Models",
        "tab_language": "Language",
        "tab_appearance": "Appearance",
        "choose_model": "Choose model:",
        "check": "Check",
        "download": "Download",
        "apply_use": "Apply & Use",
        "apply": "Apply",
        "close": "Close",
        "downloading": "Downloading…",
        "download_done": "Download complete:",
        "download_fail": "Download error:",
        "not_present": "Not present. Will be saved to:",
        "download_first": "Model not downloaded yet.",
        "model_applied": "Active model:",
        "language_choose": "Choose language:",
        "settings_applied": "Settings applied.",
        "restarting_llm": "Restarting LLM…",
        "llm_error": "LLM init error:",
        "theme_choose": "Choose theme:",
        "theme_dark": "Dark",
        "theme_light": "Light",
    },
    "it": {
        "app_title": "UE Offline Agent – Chat",
        "menu_file": "File",
        "menu_save": "Salva chat…",
        "menu_exit": "Esci",
        "menu_edit": "Modifica",
        "menu_settings": "Impostazioni…",
        "status_ready": "Pronto",
        "status_thinking": "Sto pensando…",
        "status_stop_req": "Interruzione richiesta…",
        "status_no_model": "Nessun modello selezionato. Vai su Modifica → Impostazioni…",
        "hint_ready": "Pronto. Scrivi un messaggio e premi Invio (o clicca Invia).",
        "me_label": "Tu",
        "agent_label": "Agente",
        "btn_send": "Invia",
        "btn_stop": "Stop",
        "dlg_save_title": "Salva chat",
        "dlg_chat_empty": "La chat è vuota.",
        "dlg_saved_to": "Salvata in:",
        "dlg_err_saving": "Errore salvataggio:",
        "settings_title": "Impostazioni",
        "tab_models": "Modelli",
        "tab_language": "Lingua",
        "tab_appearance": "Aspetto",
        "choose_model": "Scegli modello:",
        "check": "Controlla",
        "download": "Scarica",
        "apply_use": "Applica e usa",
        "apply": "Applica",
        "close": "Chiudi",
        "downloading": "Scaricamento in corso…",
        "download_done": "Download completato:",
        "download_fail": "Errore download:",
        "not_present": "Non presente. Verrà salvato in:",
        "download_first": "Il modello non è ancora scaricato.",
        "model_applied": "Modello attivo:",
        "language_choose": "Scegli lingua:",
        "settings_applied": "Impostazioni applicate.",
        "restarting_llm": "Riavvio LLM…",
        "llm_error": "Errore LLM:",
        "theme_choose": "Scegli tema:",
        "theme_dark": "Scuro",
        "theme_light": "Chiaro",
    },
    "es": {
        "app_title": "UE Offline Agent – Chat",
        "menu_file": "Archivo",
        "menu_save": "Guardar chat…",
        "menu_exit": "Salir",
        "menu_edit": "Editar",
        "menu_settings": "Ajustes…",
        "status_ready": "Listo",
        "status_thinking": "Pensando…",
        "status_stop_req": "Interrupción solicitada…",
        "status_no_model": "Sin modelo. Ve a Editar → Ajustes…",
        "hint_ready": "Listo. Escribe y pulsa Enter (o clic en Enviar).",
        "me_label": "Tú",
        "agent_label": "Agente",
        "btn_send": "Enviar",
        "btn_stop": "Detener",
        "dlg_save_title": "Guardar chat",
        "dlg_chat_empty": "El chat está vacío.",
        "dlg_saved_to": "Guardado en:",
        "dlg_err_saving": "Error al guardar:",
        "settings_title": "Ajustes",
        "tab_models": "Modelos",
        "tab_language": "Idioma",
        "tab_appearance": "Apariencia",
        "choose_model": "Elegir modelo:",
        "check": "Comprobar",
        "download": "Descargar",
        "apply_use": "Aplicar y usar",
        "apply": "Aplicar",
        "close": "Cerrar",
        "downloading": "Descargando…",
        "download_done": "Descarga completa:",
        "download_fail": "Error de descarga:",
        "not_present": "No presente. Se guardará en:",
        "download_first": "El modelo aún no está descargado.",
        "model_applied": "Modelo activo:",
        "language_choose": "Elegir idioma:",
        "settings_applied": "Ajustes aplicados.",
        "restarting_llm": "Reiniciando LLM…",
        "llm_error": "Error LLM:",
        "theme_choose": "Elegir tema:",
        "theme_dark": "Oscuro",
        "theme_light": "Claro",
    },
    "fr": {
        "app_title": "UE Offline Agent – Chat",
        "menu_file": "Fichier",
        "menu_save": "Enregistrer le chat…",
        "menu_exit": "Quitter",
        "menu_edit": "Édition",
        "menu_settings": "Paramètres…",
        "status_ready": "Prêt",
        "status_thinking": "Réflexion…",
        "status_stop_req": "Arrêt demandé…",
        "status_no_model": "Aucun modèle sélectionné. Allez à Édition → Paramètres…",
        "hint_ready": "Prêt. Écrivez et appuyez sur Entrée (ou cliquez Envoyer).",
        "me_label": "Vous",
        "agent_label": "Agent",
        "btn_send": "Envoyer",
        "btn_stop": "Stop",
        "dlg_save_title": "Enregistrer le chat",
        "dlg_chat_empty": "Le chat est vide.",
        "dlg_saved_to": "Enregistré dans :",
        "dlg_err_saving": "Erreur d’enregistrement :",
        "settings_title": "Paramètres",
        "tab_models": "Modèles",
        "tab_language": "Langue",
        "tab_appearance": "Apparence",
        "choose_model": "Choisir un modèle :",
        "check": "Vérifier",
        "download": "Télécharger",
        "apply_use": "Appliquer et utiliser",
        "apply": "Appliquer",
        "close": "Fermer",
        "downloading": "Téléchargement…",
        "download_done": "Téléchargement terminé :",
        "download_fail": "Erreur de téléchargement :",
        "not_present": "Absent. Sera enregistré dans :",
        "download_first": "Le modèle n’est pas encore téléchargé.",
        "model_applied": "Modèle actif :",
        "language_choose": "Choisir la langue :",
        "settings_applied": "Paramètres appliqués.",
        "restarting_llm": "Redémarrage du LLM…",
        "llm_error": "Erreur LLM :",
        "theme_choose": "Choisir le thème :",
        "theme_dark": "Sombre",
        "theme_light": "Clair",
    },
    "de": {
        "app_title": "UE Offline Agent – Chat",
        "menu_file": "Datei",
        "menu_save": "Chat speichern…",
        "menu_exit": "Beenden",
        "menu_edit": "Bearbeiten",
        "menu_settings": "Einstellungen…",
        "status_ready": "Bereit",
        "status_thinking": "Denke nach…",
        "status_stop_req": "Anhalten angefordert…",
        "status_no_model": "Kein Modell. Gehe zu Bearbeiten → Einstellungen…",
        "hint_ready": "Bereit. Nachricht schreiben und Enter drücken (oder Senden).",
        "me_label": "Du",
        "agent_label": "Agent",
        "btn_send": "Senden",
        "btn_stop": "Stopp",
        "dlg_save_title": "Chat speichern",
        "dlg_chat_empty": "Der Chat ist leer.",
        "dlg_saved_to": "Gespeichert in:",
        "dlg_err_saving": "Fehler beim Speichern:",
        "settings_title": "Einstellungen",
        "tab_models": "Modelle",
        "tab_language": "Sprache",
        "tab_appearance": "Darstellung",
        "choose_model": "Modell wählen:",
        "check": "Prüfen",
        "download": "Herunterladen",
        "apply_use": "Anwenden & nutzen",
        "apply": "Anwenden",
        "close": "Schließen",
        "downloading": "Wird heruntergeladen…",
        "download_done": "Download abgeschlossen:",
        "download_fail": "Download-Fehler:",
        "not_present": "Nicht vorhanden. Wird gespeichert unter:",
        "download_first": "Modell noch nicht heruntergeladen.",
        "model_applied": "Aktives Modell:",
        "language_choose": "Sprache wählen:",
        "settings_applied": "Einstellungen übernommen.",
        "restarting_llm": "LLM wird neu gestartet…",
        "llm_error": "LLM-Fehler:",
        "theme_choose": "Thema wählen:",
        "theme_dark": "Dunkel",
        "theme_light": "Hell",
    },
}

SYSTEM_PROMPT = {
    "en": "You are an offline assistant for Unreal Engine development. Be concise, practical, and provide code or commands when useful.",
    "it": "Sei un assistente offline pensato per aiutare nello sviluppo con Unreal Engine. Rispondi in modo conciso e pratico; fornisci codice o comandi quando utile.",
    "es": "Eres un asistente sin conexión para el desarrollo con Unreal Engine. Sé conciso y práctico; proporciona código o comandos cuando sea útil.",
    "fr": "Vous êtes un assistant hors ligne pour le développement Unreal Engine. Soyez concis et pratique ; fournissez du code ou des commandes si utile.",
    "de": "Du bist ein Offline-Assistent für die Unreal-Engine-Entwicklung. Antworte knapp und praxisnah; liefere Code oder Befehle, wenn sinnvoll.",
}

_current_lang = "it"

def set_language(lang_code: str):
    global _current_lang
    if lang_code in TRANSLATIONS:
        _current_lang = lang_code

def T(key: str) -> str:
    return TRANSLATIONS.get(_current_lang, TRANSLATIONS["en"]).get(
        key, TRANSLATIONS["en"].get(key, key)
    )

def get_system_prompt() -> str:
    return SYSTEM_PROMPT.get(_current_lang, SYSTEM_PROMPT["en"])
